services:
    app:
        image: node:14-alpine3.11
        command: npm run dev
        working_dir: /app
        container_name: samurai
        restart: always
        volumes:
            - ./:/app
        ports:
            - 3003:3003
        links:
            - db
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: samurai_postgres
        restart: always
        volumes:
            - ./.docker/pg/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=samurai
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=passw