name: deployment
on: 
  pull_request:
    branches: 
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "samurai-looping-music" #Must be unique in Heroku
          heroku_email: "ichheibemartus@outlook.com"
